kind: Deployment
apiVersion: apps/v1
metadata:
  name: ip-deroris-net
  namespace: ip-deroris-net-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ip-deroris-net
  template:
    metadata:
      labels:
        app: ip-deroris-net
    spec:
      containers:
      - args:
        image: asia.gcr.io/tactile-reason-121605/ip-deroris-net
        imagePullPolicy: Always
        name: ip-deroris-net
        ports:
        - containerPort: 3000
          protocol: TCP
      imagePullSecrets:
        - name: gcr-deroris-net
---
kind: Service
apiVersion: v1
metadata:
  name: ip-deroris-net
  namespace: ip-deroris-net-prod
spec:
  # externalTrafficPolicy: Local
#  type: LoadBalancer
  #type: NodePort
  ports:
  - name: "http-port"
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: ip-deroris-net
---
# ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: ip.deroris.net
      http:
        paths:
          - path: /
            backend:
              serviceName: ip-deroris-net
              servicePort: 80