apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  # - image: asia.gcr.io/tactile-reason-121605/ip-deroris-net
  - image: dev/ip-deroris-net
    context: ./
    docker:
      dockerfile: ./Dockerfile
    sync:
      infer:
        - 'src/**/*'
  local:
    push: false
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - ./k8s.dev.yaml
